// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: address-book.proto

package br.ufs.dcomp.ExemploRabbitMQ;

public final class AddressBookProtoBuf {
  private AddressBookProtoBuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MensagemOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string sender = 1;
    /**
     * <code>required string sender = 1;</code>
     *
     * <pre>
     * Nome do emissor
     * </pre>
     */
    boolean hasSender();
    /**
     * <code>required string sender = 1;</code>
     *
     * <pre>
     * Nome do emissor
     * </pre>
     */
    java.lang.String getSender();
    /**
     * <code>required string sender = 1;</code>
     *
     * <pre>
     * Nome do emissor
     * </pre>
     */
    com.google.protobuf.ByteString
        getSenderBytes();

    // required string date = 2;
    /**
     * <code>required string date = 2;</code>
     *
     * <pre>
     * Data de envio
     * </pre>
     */
    boolean hasDate();
    /**
     * <code>required string date = 2;</code>
     *
     * <pre>
     * Data de envio
     * </pre>
     */
    java.lang.String getDate();
    /**
     * <code>required string date = 2;</code>
     *
     * <pre>
     * Data de envio
     * </pre>
     */
    com.google.protobuf.ByteString
        getDateBytes();

    // required string time = 3;
    /**
     * <code>required string time = 3;</code>
     *
     * <pre>
     * Hora de envio
     * </pre>
     */
    boolean hasTime();
    /**
     * <code>required string time = 3;</code>
     *
     * <pre>
     * Hora de envio
     * </pre>
     */
    java.lang.String getTime();
    /**
     * <code>required string time = 3;</code>
     *
     * <pre>
     * Hora de envio
     * </pre>
     */
    com.google.protobuf.ByteString
        getTimeBytes();

    // optional string group = 4;
    /**
     * <code>optional string group = 4;</code>
     *
     * <pre>
     * Informa o nome do grupo, se a mensagem for para um grupo
     * </pre>
     */
    boolean hasGroup();
    /**
     * <code>optional string group = 4;</code>
     *
     * <pre>
     * Informa o nome do grupo, se a mensagem for para um grupo
     * </pre>
     */
    java.lang.String getGroup();
    /**
     * <code>optional string group = 4;</code>
     *
     * <pre>
     * Informa o nome do grupo, se a mensagem for para um grupo
     * </pre>
     */
    com.google.protobuf.ByteString
        getGroupBytes();

    // required .ExemploRabbitMQ.Mensagem.Conteudo content = 5;
    /**
     * <code>required .ExemploRabbitMQ.Mensagem.Conteudo content = 5;</code>
     */
    boolean hasContent();
    /**
     * <code>required .ExemploRabbitMQ.Mensagem.Conteudo content = 5;</code>
     */
    br.ufs.dcomp.ExemploRabbitMQ.AddressBookProtoBuf.Mensagem.Conteudo getContent();
    /**
     * <code>required .ExemploRabbitMQ.Mensagem.Conteudo content = 5;</code>
     */
    br.ufs.dcomp.ExemploRabbitMQ.AddressBookProtoBuf.Mensagem.ConteudoOrBuilder getContentOrBuilder();
  }
  /**
   * Protobuf type {@code ExemploRabbitMQ.Mensagem}
   */
  public static final class Mensagem extends
      com.google.protobuf.GeneratedMessage
      implements MensagemOrBuilder {
    // Use Mensagem.newBuilder() to construct.
    private Mensagem(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Mensagem(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Mensagem defaultInstance;
    public static Mensagem getDefaultInstance() {
      return defaultInstance;
    }

    public Mensagem getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Mensagem(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              sender_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              date_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              time_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              group_ = input.readBytes();
              break;
            }
            case 42: {
              br.ufs.dcomp.ExemploRabbitMQ.AddressBookProtoBuf.Mensagem.Conteudo.Builder subBuilder = null;
              if (((bitField0_ & 0x00000010) == 0x00000010)) {
                subBuilder = content_.toBuilder();
              }
              content_ = input.readMessage(br.ufs.dcomp.ExemploRabbitMQ.AddressBookProtoBuf.Mensagem.Conteudo.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(content_);
                content_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000010;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return br.ufs.dcomp.ExemploRabbitMQ.AddressBookProtoBuf.internal_static_ExemploRabbitMQ_Mensagem_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return br.ufs.dcomp.ExemploRabbitMQ.AddressBookProtoBuf.internal_static_ExemploRabbitMQ_Mensagem_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              br.ufs.dcomp.ExemploRabbitMQ.AddressBookProtoBuf.Mensagem.class, br.ufs.dcomp.ExemploRabbitMQ.AddressBookProtoBuf.Mensagem.Builder.class);
    }

    public static com.google.protobuf.Parser<Mensagem> PARSER =
        new com.google.protobuf.AbstractParser<Mensagem>() {
      public Mensagem parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Mensagem(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Mensagem> getParserForType() {
      return PARSER;
    }

    public interface ConteudoOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // required string type = 1;
      /**
       * <code>required string type = 1;</code>
       *
       * <pre>
       * Tipo do conteúdo no padrão de tipos MIME. Exemplos: "text/plain", "image/png" 
       * </pre>
       */
      boolean hasType();
      /**
       * <code>required string type = 1;</code>
       *
       * <pre>
       * Tipo do conteúdo no padrão de tipos MIME. Exemplos: "text/plain", "image/png" 
       * </pre>
       */
      java.lang.String getType();
      /**
       * <code>required string type = 1;</code>
       *
       * <pre>
       * Tipo do conteúdo no padrão de tipos MIME. Exemplos: "text/plain", "image/png" 
       * </pre>
       */
      com.google.protobuf.ByteString
          getTypeBytes();

      // required bytes body = 2;
      /**
       * <code>required bytes body = 2;</code>
       *
       * <pre>
       * Sequência de bytes que compõe o corpo da mensagem
       * </pre>
       */
      boolean hasBody();
      /**
       * <code>required bytes body = 2;</code>
       *
       * <pre>
       * Sequência de bytes que compõe o corpo da mensagem
       * </pre>
       */
      com.google.protobuf.ByteString getBody();

      // optional string name = 3;
      /**
       * <code>optional string name = 3;</code>
       *
       * <pre>
       * Nome do conteúdo, se existente. Exemplos: "logo_ufs.png", "index.html"
       * </pre>
       */
      boolean hasName();
      /**
       * <code>optional string name = 3;</code>
       *
       * <pre>
       * Nome do conteúdo, se existente. Exemplos: "logo_ufs.png", "index.html"
       * </pre>
       */
      java.lang.String getName();
      /**
       * <code>optional string name = 3;</code>
       *
       * <pre>
       * Nome do conteúdo, se existente. Exemplos: "logo_ufs.png", "index.html"
       * </pre>
       */
      com.google.protobuf.ByteString
          getNameBytes();
    }
    /**
     * Protobuf type {@code ExemploRabbitMQ.Mensagem.Conteudo}
     */
    public static final class Conteudo extends
        com.google.protobuf.GeneratedMessage
        implements ConteudoOrBuilder {
      // Use Conteudo.newBuilder() to construct.
      private Conteudo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private Conteudo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final Conteudo defaultInstance;
      public static Conteudo getDefaultInstance() {
        return defaultInstance;
      }

      public Conteudo getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private Conteudo(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                bitField0_ |= 0x00000001;
                type_ = input.readBytes();
                break;
              }
              case 18: {
                bitField0_ |= 0x00000002;
                body_ = input.readBytes();
                break;
              }
              case 26: {
                bitField0_ |= 0x00000004;
                name_ = input.readBytes();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return br.ufs.dcomp.ExemploRabbitMQ.AddressBookProtoBuf.internal_static_ExemploRabbitMQ_Mensagem_Conteudo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return br.ufs.dcomp.ExemploRabbitMQ.AddressBookProtoBuf.internal_static_ExemploRabbitMQ_Mensagem_Conteudo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                br.ufs.dcomp.ExemploRabbitMQ.AddressBookProtoBuf.Mensagem.Conteudo.class, br.ufs.dcomp.ExemploRabbitMQ.AddressBookProtoBuf.Mensagem.Conteudo.Builder.class);
      }

      public static com.google.protobuf.Parser<Conteudo> PARSER =
          new com.google.protobuf.AbstractParser<Conteudo>() {
        public Conteudo parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Conteudo(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<Conteudo> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // required string type = 1;
      public static final int TYPE_FIELD_NUMBER = 1;
      private java.lang.Object type_;
      /**
       * <code>required string type = 1;</code>
       *
       * <pre>
       * Tipo do conteúdo no padrão de tipos MIME. Exemplos: "text/plain", "image/png" 
       * </pre>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string type = 1;</code>
       *
       * <pre>
       * Tipo do conteúdo no padrão de tipos MIME. Exemplos: "text/plain", "image/png" 
       * </pre>
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            type_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string type = 1;</code>
       *
       * <pre>
       * Tipo do conteúdo no padrão de tipos MIME. Exemplos: "text/plain", "image/png" 
       * </pre>
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // required bytes body = 2;
      public static final int BODY_FIELD_NUMBER = 2;
      private com.google.protobuf.ByteString body_;
      /**
       * <code>required bytes body = 2;</code>
       *
       * <pre>
       * Sequência de bytes que compõe o corpo da mensagem
       * </pre>
       */
      public boolean hasBody() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bytes body = 2;</code>
       *
       * <pre>
       * Sequência de bytes que compõe o corpo da mensagem
       * </pre>
       */
      public com.google.protobuf.ByteString getBody() {
        return body_;
      }

      // optional string name = 3;
      public static final int NAME_FIELD_NUMBER = 3;
      private java.lang.Object name_;
      /**
       * <code>optional string name = 3;</code>
       *
       * <pre>
       * Nome do conteúdo, se existente. Exemplos: "logo_ufs.png", "index.html"
       * </pre>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string name = 3;</code>
       *
       * <pre>
       * Nome do conteúdo, se existente. Exemplos: "logo_ufs.png", "index.html"
       * </pre>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string name = 3;</code>
       *
       * <pre>
       * Nome do conteúdo, se existente. Exemplos: "logo_ufs.png", "index.html"
       * </pre>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private void initFields() {
        type_ = "";
        body_ = com.google.protobuf.ByteString.EMPTY;
        name_ = "";
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        if (!hasType()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasBody()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getTypeBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, body_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeBytes(3, getNameBytes());
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getTypeBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, body_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(3, getNameBytes());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static br.ufs.dcomp.ExemploRabbitMQ.AddressBookProtoBuf.Mensagem.Conteudo parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static br.ufs.dcomp.ExemploRabbitMQ.AddressBookProtoBuf.Mensagem.Conteudo parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static br.ufs.dcomp.ExemploRabbitMQ.AddressBookProtoBuf.Mensagem.Conteudo parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static br.ufs.dcomp.ExemploRabbitMQ.AddressBookProtoBuf.Mensagem.Conteudo parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static br.ufs.dcomp.ExemploRabbitMQ.AddressBookProtoBuf.Mensagem.Conteudo parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static br.ufs.dcomp.ExemploRabbitMQ.AddressBookProtoBuf.Mensagem.Conteudo parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static br.ufs.dcomp.ExemploRabbitMQ.AddressBookProtoBuf.Mensagem.Conteudo parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static br.ufs.dcomp.ExemploRabbitMQ.AddressBookProtoBuf.Mensagem.Conteudo parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static br.ufs.dcomp.ExemploRabbitMQ.AddressBookProtoBuf.Mensagem.Conteudo parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static br.ufs.dcomp.ExemploRabbitMQ.AddressBookProtoBuf.Mensagem.Conteudo parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(br.ufs.dcomp.ExemploRabbitMQ.AddressBookProtoBuf.Mensagem.Conteudo prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code ExemploRabbitMQ.Mensagem.Conteudo}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements br.ufs.dcomp.ExemploRabbitMQ.AddressBookProtoBuf.Mensagem.ConteudoOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return br.ufs.dcomp.ExemploRabbitMQ.AddressBookProtoBuf.internal_static_ExemploRabbitMQ_Mensagem_Conteudo_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return br.ufs.dcomp.ExemploRabbitMQ.AddressBookProtoBuf.internal_static_ExemploRabbitMQ_Mensagem_Conteudo_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  br.ufs.dcomp.ExemploRabbitMQ.AddressBookProtoBuf.Mensagem.Conteudo.class, br.ufs.dcomp.ExemploRabbitMQ.AddressBookProtoBuf.Mensagem.Conteudo.Builder.class);
        }

        // Construct using br.ufs.dcomp.ExemploRabbitMQ.AddressBookProtoBuf.Mensagem.Conteudo.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          type_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          body_ = com.google.protobuf.ByteString.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000002);
          name_ = "";
          bitField0_ = (bitField0_ & ~0x00000004);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return br.ufs.dcomp.ExemploRabbitMQ.AddressBookProtoBuf.internal_static_ExemploRabbitMQ_Mensagem_Conteudo_descriptor;
        }

        public br.ufs.dcomp.ExemploRabbitMQ.AddressBookProtoBuf.Mensagem.Conteudo getDefaultInstanceForType() {
          return br.ufs.dcomp.ExemploRabbitMQ.AddressBookProtoBuf.Mensagem.Conteudo.getDefaultInstance();
        }

        public br.ufs.dcomp.ExemploRabbitMQ.AddressBookProtoBuf.Mensagem.Conteudo build() {
          br.ufs.dcomp.ExemploRabbitMQ.AddressBookProtoBuf.Mensagem.Conteudo result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public br.ufs.dcomp.ExemploRabbitMQ.AddressBookProtoBuf.Mensagem.Conteudo buildPartial() {
          br.ufs.dcomp.ExemploRabbitMQ.AddressBookProtoBuf.Mensagem.Conteudo result = new br.ufs.dcomp.ExemploRabbitMQ.AddressBookProtoBuf.Mensagem.Conteudo(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.type_ = type_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.body_ = body_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.name_ = name_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof br.ufs.dcomp.ExemploRabbitMQ.AddressBookProtoBuf.Mensagem.Conteudo) {
            return mergeFrom((br.ufs.dcomp.ExemploRabbitMQ.AddressBookProtoBuf.Mensagem.Conteudo)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(br.ufs.dcomp.ExemploRabbitMQ.AddressBookProtoBuf.Mensagem.Conteudo other) {
          if (other == br.ufs.dcomp.ExemploRabbitMQ.AddressBookProtoBuf.Mensagem.Conteudo.getDefaultInstance()) return this;
          if (other.hasType()) {
            bitField0_ |= 0x00000001;
            type_ = other.type_;
            onChanged();
          }
          if (other.hasBody()) {
            setBody(other.getBody());
          }
          if (other.hasName()) {
            bitField0_ |= 0x00000004;
            name_ = other.name_;
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasType()) {
            
            return false;
          }
          if (!hasBody()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          br.ufs.dcomp.ExemploRabbitMQ.AddressBookProtoBuf.Mensagem.Conteudo parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (br.ufs.dcomp.ExemploRabbitMQ.AddressBookProtoBuf.Mensagem.Conteudo) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // required string type = 1;
        private java.lang.Object type_ = "";
        /**
         * <code>required string type = 1;</code>
         *
         * <pre>
         * Tipo do conteúdo no padrão de tipos MIME. Exemplos: "text/plain", "image/png" 
         * </pre>
         */
        public boolean hasType() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required string type = 1;</code>
         *
         * <pre>
         * Tipo do conteúdo no padrão de tipos MIME. Exemplos: "text/plain", "image/png" 
         * </pre>
         */
        public java.lang.String getType() {
          java.lang.Object ref = type_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            type_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string type = 1;</code>
         *
         * <pre>
         * Tipo do conteúdo no padrão de tipos MIME. Exemplos: "text/plain", "image/png" 
         * </pre>
         */
        public com.google.protobuf.ByteString
            getTypeBytes() {
          java.lang.Object ref = type_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            type_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string type = 1;</code>
         *
         * <pre>
         * Tipo do conteúdo no padrão de tipos MIME. Exemplos: "text/plain", "image/png" 
         * </pre>
         */
        public Builder setType(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          type_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string type = 1;</code>
         *
         * <pre>
         * Tipo do conteúdo no padrão de tipos MIME. Exemplos: "text/plain", "image/png" 
         * </pre>
         */
        public Builder clearType() {
          bitField0_ = (bitField0_ & ~0x00000001);
          type_ = getDefaultInstance().getType();
          onChanged();
          return this;
        }
        /**
         * <code>required string type = 1;</code>
         *
         * <pre>
         * Tipo do conteúdo no padrão de tipos MIME. Exemplos: "text/plain", "image/png" 
         * </pre>
         */
        public Builder setTypeBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          type_ = value;
          onChanged();
          return this;
        }

        // required bytes body = 2;
        private com.google.protobuf.ByteString body_ = com.google.protobuf.ByteString.EMPTY;
        /**
         * <code>required bytes body = 2;</code>
         *
         * <pre>
         * Sequência de bytes que compõe o corpo da mensagem
         * </pre>
         */
        public boolean hasBody() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required bytes body = 2;</code>
         *
         * <pre>
         * Sequência de bytes que compõe o corpo da mensagem
         * </pre>
         */
        public com.google.protobuf.ByteString getBody() {
          return body_;
        }
        /**
         * <code>required bytes body = 2;</code>
         *
         * <pre>
         * Sequência de bytes que compõe o corpo da mensagem
         * </pre>
         */
        public Builder setBody(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          body_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required bytes body = 2;</code>
         *
         * <pre>
         * Sequência de bytes que compõe o corpo da mensagem
         * </pre>
         */
        public Builder clearBody() {
          bitField0_ = (bitField0_ & ~0x00000002);
          body_ = getDefaultInstance().getBody();
          onChanged();
          return this;
        }

        // optional string name = 3;
        private java.lang.Object name_ = "";
        /**
         * <code>optional string name = 3;</code>
         *
         * <pre>
         * Nome do conteúdo, se existente. Exemplos: "logo_ufs.png", "index.html"
         * </pre>
         */
        public boolean hasName() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>optional string name = 3;</code>
         *
         * <pre>
         * Nome do conteúdo, se existente. Exemplos: "logo_ufs.png", "index.html"
         * </pre>
         */
        public java.lang.String getName() {
          java.lang.Object ref = name_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            name_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string name = 3;</code>
         *
         * <pre>
         * Nome do conteúdo, se existente. Exemplos: "logo_ufs.png", "index.html"
         * </pre>
         */
        public com.google.protobuf.ByteString
            getNameBytes() {
          java.lang.Object ref = name_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            name_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string name = 3;</code>
         *
         * <pre>
         * Nome do conteúdo, se existente. Exemplos: "logo_ufs.png", "index.html"
         * </pre>
         */
        public Builder setName(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          name_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string name = 3;</code>
         *
         * <pre>
         * Nome do conteúdo, se existente. Exemplos: "logo_ufs.png", "index.html"
         * </pre>
         */
        public Builder clearName() {
          bitField0_ = (bitField0_ & ~0x00000004);
          name_ = getDefaultInstance().getName();
          onChanged();
          return this;
        }
        /**
         * <code>optional string name = 3;</code>
         *
         * <pre>
         * Nome do conteúdo, se existente. Exemplos: "logo_ufs.png", "index.html"
         * </pre>
         */
        public Builder setNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          name_ = value;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:ExemploRabbitMQ.Mensagem.Conteudo)
      }

      static {
        defaultInstance = new Conteudo(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:ExemploRabbitMQ.Mensagem.Conteudo)
    }

    private int bitField0_;
    // required string sender = 1;
    public static final int SENDER_FIELD_NUMBER = 1;
    private java.lang.Object sender_;
    /**
     * <code>required string sender = 1;</code>
     *
     * <pre>
     * Nome do emissor
     * </pre>
     */
    public boolean hasSender() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string sender = 1;</code>
     *
     * <pre>
     * Nome do emissor
     * </pre>
     */
    public java.lang.String getSender() {
      java.lang.Object ref = sender_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sender_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string sender = 1;</code>
     *
     * <pre>
     * Nome do emissor
     * </pre>
     */
    public com.google.protobuf.ByteString
        getSenderBytes() {
      java.lang.Object ref = sender_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sender_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string date = 2;
    public static final int DATE_FIELD_NUMBER = 2;
    private java.lang.Object date_;
    /**
     * <code>required string date = 2;</code>
     *
     * <pre>
     * Data de envio
     * </pre>
     */
    public boolean hasDate() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string date = 2;</code>
     *
     * <pre>
     * Data de envio
     * </pre>
     */
    public java.lang.String getDate() {
      java.lang.Object ref = date_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          date_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string date = 2;</code>
     *
     * <pre>
     * Data de envio
     * </pre>
     */
    public com.google.protobuf.ByteString
        getDateBytes() {
      java.lang.Object ref = date_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        date_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string time = 3;
    public static final int TIME_FIELD_NUMBER = 3;
    private java.lang.Object time_;
    /**
     * <code>required string time = 3;</code>
     *
     * <pre>
     * Hora de envio
     * </pre>
     */
    public boolean hasTime() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string time = 3;</code>
     *
     * <pre>
     * Hora de envio
     * </pre>
     */
    public java.lang.String getTime() {
      java.lang.Object ref = time_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          time_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string time = 3;</code>
     *
     * <pre>
     * Hora de envio
     * </pre>
     */
    public com.google.protobuf.ByteString
        getTimeBytes() {
      java.lang.Object ref = time_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        time_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string group = 4;
    public static final int GROUP_FIELD_NUMBER = 4;
    private java.lang.Object group_;
    /**
     * <code>optional string group = 4;</code>
     *
     * <pre>
     * Informa o nome do grupo, se a mensagem for para um grupo
     * </pre>
     */
    public boolean hasGroup() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string group = 4;</code>
     *
     * <pre>
     * Informa o nome do grupo, se a mensagem for para um grupo
     * </pre>
     */
    public java.lang.String getGroup() {
      java.lang.Object ref = group_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          group_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string group = 4;</code>
     *
     * <pre>
     * Informa o nome do grupo, se a mensagem for para um grupo
     * </pre>
     */
    public com.google.protobuf.ByteString
        getGroupBytes() {
      java.lang.Object ref = group_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        group_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required .ExemploRabbitMQ.Mensagem.Conteudo content = 5;
    public static final int CONTENT_FIELD_NUMBER = 5;
    private br.ufs.dcomp.ExemploRabbitMQ.AddressBookProtoBuf.Mensagem.Conteudo content_;
    /**
     * <code>required .ExemploRabbitMQ.Mensagem.Conteudo content = 5;</code>
     */
    public boolean hasContent() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required .ExemploRabbitMQ.Mensagem.Conteudo content = 5;</code>
     */
    public br.ufs.dcomp.ExemploRabbitMQ.AddressBookProtoBuf.Mensagem.Conteudo getContent() {
      return content_;
    }
    /**
     * <code>required .ExemploRabbitMQ.Mensagem.Conteudo content = 5;</code>
     */
    public br.ufs.dcomp.ExemploRabbitMQ.AddressBookProtoBuf.Mensagem.ConteudoOrBuilder getContentOrBuilder() {
      return content_;
    }

    private void initFields() {
      sender_ = "";
      date_ = "";
      time_ = "";
      group_ = "";
      content_ = br.ufs.dcomp.ExemploRabbitMQ.AddressBookProtoBuf.Mensagem.Conteudo.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasSender()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDate()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasContent()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getContent().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getSenderBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getDateBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getTimeBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getGroupBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeMessage(5, content_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getSenderBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getDateBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getTimeBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getGroupBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, content_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static br.ufs.dcomp.ExemploRabbitMQ.AddressBookProtoBuf.Mensagem parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.ufs.dcomp.ExemploRabbitMQ.AddressBookProtoBuf.Mensagem parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.ufs.dcomp.ExemploRabbitMQ.AddressBookProtoBuf.Mensagem parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.ufs.dcomp.ExemploRabbitMQ.AddressBookProtoBuf.Mensagem parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.ufs.dcomp.ExemploRabbitMQ.AddressBookProtoBuf.Mensagem parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static br.ufs.dcomp.ExemploRabbitMQ.AddressBookProtoBuf.Mensagem parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static br.ufs.dcomp.ExemploRabbitMQ.AddressBookProtoBuf.Mensagem parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static br.ufs.dcomp.ExemploRabbitMQ.AddressBookProtoBuf.Mensagem parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static br.ufs.dcomp.ExemploRabbitMQ.AddressBookProtoBuf.Mensagem parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static br.ufs.dcomp.ExemploRabbitMQ.AddressBookProtoBuf.Mensagem parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(br.ufs.dcomp.ExemploRabbitMQ.AddressBookProtoBuf.Mensagem prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ExemploRabbitMQ.Mensagem}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements br.ufs.dcomp.ExemploRabbitMQ.AddressBookProtoBuf.MensagemOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return br.ufs.dcomp.ExemploRabbitMQ.AddressBookProtoBuf.internal_static_ExemploRabbitMQ_Mensagem_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return br.ufs.dcomp.ExemploRabbitMQ.AddressBookProtoBuf.internal_static_ExemploRabbitMQ_Mensagem_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                br.ufs.dcomp.ExemploRabbitMQ.AddressBookProtoBuf.Mensagem.class, br.ufs.dcomp.ExemploRabbitMQ.AddressBookProtoBuf.Mensagem.Builder.class);
      }

      // Construct using br.ufs.dcomp.ExemploRabbitMQ.AddressBookProtoBuf.Mensagem.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getContentFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        sender_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        date_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        time_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        group_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        if (contentBuilder_ == null) {
          content_ = br.ufs.dcomp.ExemploRabbitMQ.AddressBookProtoBuf.Mensagem.Conteudo.getDefaultInstance();
        } else {
          contentBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return br.ufs.dcomp.ExemploRabbitMQ.AddressBookProtoBuf.internal_static_ExemploRabbitMQ_Mensagem_descriptor;
      }

      public br.ufs.dcomp.ExemploRabbitMQ.AddressBookProtoBuf.Mensagem getDefaultInstanceForType() {
        return br.ufs.dcomp.ExemploRabbitMQ.AddressBookProtoBuf.Mensagem.getDefaultInstance();
      }

      public br.ufs.dcomp.ExemploRabbitMQ.AddressBookProtoBuf.Mensagem build() {
        br.ufs.dcomp.ExemploRabbitMQ.AddressBookProtoBuf.Mensagem result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public br.ufs.dcomp.ExemploRabbitMQ.AddressBookProtoBuf.Mensagem buildPartial() {
        br.ufs.dcomp.ExemploRabbitMQ.AddressBookProtoBuf.Mensagem result = new br.ufs.dcomp.ExemploRabbitMQ.AddressBookProtoBuf.Mensagem(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.sender_ = sender_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.date_ = date_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.time_ = time_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.group_ = group_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        if (contentBuilder_ == null) {
          result.content_ = content_;
        } else {
          result.content_ = contentBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof br.ufs.dcomp.ExemploRabbitMQ.AddressBookProtoBuf.Mensagem) {
          return mergeFrom((br.ufs.dcomp.ExemploRabbitMQ.AddressBookProtoBuf.Mensagem)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(br.ufs.dcomp.ExemploRabbitMQ.AddressBookProtoBuf.Mensagem other) {
        if (other == br.ufs.dcomp.ExemploRabbitMQ.AddressBookProtoBuf.Mensagem.getDefaultInstance()) return this;
        if (other.hasSender()) {
          bitField0_ |= 0x00000001;
          sender_ = other.sender_;
          onChanged();
        }
        if (other.hasDate()) {
          bitField0_ |= 0x00000002;
          date_ = other.date_;
          onChanged();
        }
        if (other.hasTime()) {
          bitField0_ |= 0x00000004;
          time_ = other.time_;
          onChanged();
        }
        if (other.hasGroup()) {
          bitField0_ |= 0x00000008;
          group_ = other.group_;
          onChanged();
        }
        if (other.hasContent()) {
          mergeContent(other.getContent());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSender()) {
          
          return false;
        }
        if (!hasDate()) {
          
          return false;
        }
        if (!hasTime()) {
          
          return false;
        }
        if (!hasContent()) {
          
          return false;
        }
        if (!getContent().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        br.ufs.dcomp.ExemploRabbitMQ.AddressBookProtoBuf.Mensagem parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (br.ufs.dcomp.ExemploRabbitMQ.AddressBookProtoBuf.Mensagem) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string sender = 1;
      private java.lang.Object sender_ = "";
      /**
       * <code>required string sender = 1;</code>
       *
       * <pre>
       * Nome do emissor
       * </pre>
       */
      public boolean hasSender() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string sender = 1;</code>
       *
       * <pre>
       * Nome do emissor
       * </pre>
       */
      public java.lang.String getSender() {
        java.lang.Object ref = sender_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          sender_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string sender = 1;</code>
       *
       * <pre>
       * Nome do emissor
       * </pre>
       */
      public com.google.protobuf.ByteString
          getSenderBytes() {
        java.lang.Object ref = sender_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sender_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string sender = 1;</code>
       *
       * <pre>
       * Nome do emissor
       * </pre>
       */
      public Builder setSender(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        sender_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string sender = 1;</code>
       *
       * <pre>
       * Nome do emissor
       * </pre>
       */
      public Builder clearSender() {
        bitField0_ = (bitField0_ & ~0x00000001);
        sender_ = getDefaultInstance().getSender();
        onChanged();
        return this;
      }
      /**
       * <code>required string sender = 1;</code>
       *
       * <pre>
       * Nome do emissor
       * </pre>
       */
      public Builder setSenderBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        sender_ = value;
        onChanged();
        return this;
      }

      // required string date = 2;
      private java.lang.Object date_ = "";
      /**
       * <code>required string date = 2;</code>
       *
       * <pre>
       * Data de envio
       * </pre>
       */
      public boolean hasDate() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string date = 2;</code>
       *
       * <pre>
       * Data de envio
       * </pre>
       */
      public java.lang.String getDate() {
        java.lang.Object ref = date_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          date_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string date = 2;</code>
       *
       * <pre>
       * Data de envio
       * </pre>
       */
      public com.google.protobuf.ByteString
          getDateBytes() {
        java.lang.Object ref = date_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          date_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string date = 2;</code>
       *
       * <pre>
       * Data de envio
       * </pre>
       */
      public Builder setDate(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        date_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string date = 2;</code>
       *
       * <pre>
       * Data de envio
       * </pre>
       */
      public Builder clearDate() {
        bitField0_ = (bitField0_ & ~0x00000002);
        date_ = getDefaultInstance().getDate();
        onChanged();
        return this;
      }
      /**
       * <code>required string date = 2;</code>
       *
       * <pre>
       * Data de envio
       * </pre>
       */
      public Builder setDateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        date_ = value;
        onChanged();
        return this;
      }

      // required string time = 3;
      private java.lang.Object time_ = "";
      /**
       * <code>required string time = 3;</code>
       *
       * <pre>
       * Hora de envio
       * </pre>
       */
      public boolean hasTime() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string time = 3;</code>
       *
       * <pre>
       * Hora de envio
       * </pre>
       */
      public java.lang.String getTime() {
        java.lang.Object ref = time_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          time_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string time = 3;</code>
       *
       * <pre>
       * Hora de envio
       * </pre>
       */
      public com.google.protobuf.ByteString
          getTimeBytes() {
        java.lang.Object ref = time_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          time_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string time = 3;</code>
       *
       * <pre>
       * Hora de envio
       * </pre>
       */
      public Builder setTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string time = 3;</code>
       *
       * <pre>
       * Hora de envio
       * </pre>
       */
      public Builder clearTime() {
        bitField0_ = (bitField0_ & ~0x00000004);
        time_ = getDefaultInstance().getTime();
        onChanged();
        return this;
      }
      /**
       * <code>required string time = 3;</code>
       *
       * <pre>
       * Hora de envio
       * </pre>
       */
      public Builder setTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        time_ = value;
        onChanged();
        return this;
      }

      // optional string group = 4;
      private java.lang.Object group_ = "";
      /**
       * <code>optional string group = 4;</code>
       *
       * <pre>
       * Informa o nome do grupo, se a mensagem for para um grupo
       * </pre>
       */
      public boolean hasGroup() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string group = 4;</code>
       *
       * <pre>
       * Informa o nome do grupo, se a mensagem for para um grupo
       * </pre>
       */
      public java.lang.String getGroup() {
        java.lang.Object ref = group_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          group_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string group = 4;</code>
       *
       * <pre>
       * Informa o nome do grupo, se a mensagem for para um grupo
       * </pre>
       */
      public com.google.protobuf.ByteString
          getGroupBytes() {
        java.lang.Object ref = group_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          group_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string group = 4;</code>
       *
       * <pre>
       * Informa o nome do grupo, se a mensagem for para um grupo
       * </pre>
       */
      public Builder setGroup(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        group_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string group = 4;</code>
       *
       * <pre>
       * Informa o nome do grupo, se a mensagem for para um grupo
       * </pre>
       */
      public Builder clearGroup() {
        bitField0_ = (bitField0_ & ~0x00000008);
        group_ = getDefaultInstance().getGroup();
        onChanged();
        return this;
      }
      /**
       * <code>optional string group = 4;</code>
       *
       * <pre>
       * Informa o nome do grupo, se a mensagem for para um grupo
       * </pre>
       */
      public Builder setGroupBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        group_ = value;
        onChanged();
        return this;
      }

      // required .ExemploRabbitMQ.Mensagem.Conteudo content = 5;
      private br.ufs.dcomp.ExemploRabbitMQ.AddressBookProtoBuf.Mensagem.Conteudo content_ = br.ufs.dcomp.ExemploRabbitMQ.AddressBookProtoBuf.Mensagem.Conteudo.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          br.ufs.dcomp.ExemploRabbitMQ.AddressBookProtoBuf.Mensagem.Conteudo, br.ufs.dcomp.ExemploRabbitMQ.AddressBookProtoBuf.Mensagem.Conteudo.Builder, br.ufs.dcomp.ExemploRabbitMQ.AddressBookProtoBuf.Mensagem.ConteudoOrBuilder> contentBuilder_;
      /**
       * <code>required .ExemploRabbitMQ.Mensagem.Conteudo content = 5;</code>
       */
      public boolean hasContent() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required .ExemploRabbitMQ.Mensagem.Conteudo content = 5;</code>
       */
      public br.ufs.dcomp.ExemploRabbitMQ.AddressBookProtoBuf.Mensagem.Conteudo getContent() {
        if (contentBuilder_ == null) {
          return content_;
        } else {
          return contentBuilder_.getMessage();
        }
      }
      /**
       * <code>required .ExemploRabbitMQ.Mensagem.Conteudo content = 5;</code>
       */
      public Builder setContent(br.ufs.dcomp.ExemploRabbitMQ.AddressBookProtoBuf.Mensagem.Conteudo value) {
        if (contentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          content_ = value;
          onChanged();
        } else {
          contentBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>required .ExemploRabbitMQ.Mensagem.Conteudo content = 5;</code>
       */
      public Builder setContent(
          br.ufs.dcomp.ExemploRabbitMQ.AddressBookProtoBuf.Mensagem.Conteudo.Builder builderForValue) {
        if (contentBuilder_ == null) {
          content_ = builderForValue.build();
          onChanged();
        } else {
          contentBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>required .ExemploRabbitMQ.Mensagem.Conteudo content = 5;</code>
       */
      public Builder mergeContent(br.ufs.dcomp.ExemploRabbitMQ.AddressBookProtoBuf.Mensagem.Conteudo value) {
        if (contentBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010) &&
              content_ != br.ufs.dcomp.ExemploRabbitMQ.AddressBookProtoBuf.Mensagem.Conteudo.getDefaultInstance()) {
            content_ =
              br.ufs.dcomp.ExemploRabbitMQ.AddressBookProtoBuf.Mensagem.Conteudo.newBuilder(content_).mergeFrom(value).buildPartial();
          } else {
            content_ = value;
          }
          onChanged();
        } else {
          contentBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>required .ExemploRabbitMQ.Mensagem.Conteudo content = 5;</code>
       */
      public Builder clearContent() {
        if (contentBuilder_ == null) {
          content_ = br.ufs.dcomp.ExemploRabbitMQ.AddressBookProtoBuf.Mensagem.Conteudo.getDefaultInstance();
          onChanged();
        } else {
          contentBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      /**
       * <code>required .ExemploRabbitMQ.Mensagem.Conteudo content = 5;</code>
       */
      public br.ufs.dcomp.ExemploRabbitMQ.AddressBookProtoBuf.Mensagem.Conteudo.Builder getContentBuilder() {
        bitField0_ |= 0x00000010;
        onChanged();
        return getContentFieldBuilder().getBuilder();
      }
      /**
       * <code>required .ExemploRabbitMQ.Mensagem.Conteudo content = 5;</code>
       */
      public br.ufs.dcomp.ExemploRabbitMQ.AddressBookProtoBuf.Mensagem.ConteudoOrBuilder getContentOrBuilder() {
        if (contentBuilder_ != null) {
          return contentBuilder_.getMessageOrBuilder();
        } else {
          return content_;
        }
      }
      /**
       * <code>required .ExemploRabbitMQ.Mensagem.Conteudo content = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          br.ufs.dcomp.ExemploRabbitMQ.AddressBookProtoBuf.Mensagem.Conteudo, br.ufs.dcomp.ExemploRabbitMQ.AddressBookProtoBuf.Mensagem.Conteudo.Builder, br.ufs.dcomp.ExemploRabbitMQ.AddressBookProtoBuf.Mensagem.ConteudoOrBuilder> 
          getContentFieldBuilder() {
        if (contentBuilder_ == null) {
          contentBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              br.ufs.dcomp.ExemploRabbitMQ.AddressBookProtoBuf.Mensagem.Conteudo, br.ufs.dcomp.ExemploRabbitMQ.AddressBookProtoBuf.Mensagem.Conteudo.Builder, br.ufs.dcomp.ExemploRabbitMQ.AddressBookProtoBuf.Mensagem.ConteudoOrBuilder>(
                  content_,
                  getParentForChildren(),
                  isClean());
          content_ = null;
        }
        return contentBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:ExemploRabbitMQ.Mensagem)
    }

    static {
      defaultInstance = new Mensagem(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ExemploRabbitMQ.Mensagem)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ExemploRabbitMQ_Mensagem_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ExemploRabbitMQ_Mensagem_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ExemploRabbitMQ_Mensagem_Conteudo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ExemploRabbitMQ_Mensagem_Conteudo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022address-book.proto\022\017ExemploRabbitMQ\"\260\001" +
      "\n\010Mensagem\022\016\n\006sender\030\001 \002(\t\022\014\n\004date\030\002 \002(\t" +
      "\022\014\n\004time\030\003 \002(\t\022\r\n\005group\030\004 \001(\t\0223\n\007content" +
      "\030\005 \002(\0132\".ExemploRabbitMQ.Mensagem.Conteu" +
      "do\0324\n\010Conteudo\022\014\n\004type\030\001 \002(\t\022\014\n\004body\030\002 \002" +
      "(\014\022\014\n\004name\030\003 \001(\tB3\n\034br.ufs.dcomp.Exemplo" +
      "RabbitMQB\023AddressBookProtoBuf"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_ExemploRabbitMQ_Mensagem_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_ExemploRabbitMQ_Mensagem_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ExemploRabbitMQ_Mensagem_descriptor,
              new java.lang.String[] { "Sender", "Date", "Time", "Group", "Content", });
          internal_static_ExemploRabbitMQ_Mensagem_Conteudo_descriptor =
            internal_static_ExemploRabbitMQ_Mensagem_descriptor.getNestedTypes().get(0);
          internal_static_ExemploRabbitMQ_Mensagem_Conteudo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ExemploRabbitMQ_Mensagem_Conteudo_descriptor,
              new java.lang.String[] { "Type", "Body", "Name", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
